services:
  - type: web
    name: leadlist-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 